### ISSUE TITLE
BCM7 conflict with SPI0-CS1 when SPI is enabled

### ISSUE THREAD

**Issue by gecko242** [gecko242/CarPiHat#1]
BCM7 (used for reverse input) conflicts with SPI0-CS1 when SPI is enabled.

Change documentation to reflect this and explain.

**Comment by gecko242** [comment]
Note added in 2c069e3784c7c2fa388563c0b161fe83ef122039

**Comment by jasano** [comment]
I'm sure this will end up being some kind of user error, but on OAP 12.0 when I follow the CarPiHat instructions to enable the real-time clock, I get this message if I try to manually run the command from rc.local:

pi@raspberrypi:~ $ sudo echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device hwclock -s
bash: /sys/class/i2c-adapter/i2c-1/new_device: Permission denied
pi@raspberrypi:~ $ 

Any ideas how to fix this? Please let me know if this the wrong place to post questions.

**Comment by gecko242** [comment]
Hi @jasano,

The best place to ask questions would be via email, or the Tindie forums. As for your issue, when you run the command:

`sudo echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device hwclock -s`

The second half of the command will not be interpreted as root. Try first opening a root shell:

`sudo bash`

And then running the command again.

**Comment by jasano** [comment]
Hey I just saw this email. Thanks for the reply!

I'm not sure I'm doing git right but I tried to make a pull request with
some comments on your Readme. Hope they're helpful.

I posted a few questions on your Blue Wave Studio forum post. Let me know
if you'd like me to take down the question from that thread. But, I'm
guessing other users might find your responses helpful.

Thanks for the help.
